config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', 
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios do
    put :sort, on: :collection
  end
  get 'react-items', to: 'portfolios#react'

  get 'about-me', to: "pages#about"
  get 'contact', to: "pages#contact"

  resources :posts do
    member do
      post :toggle_status
    end
  end

  root to: "pages#home"
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies, dependent: :destroy
  accepts_nested_attributes_for :technologies, 
                                reject_if: lambda { |attr| attr['name'].blank? }

  validates_presence_of :title, :body

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  def self.react
    where(subtitle: 'React')
  end

  def self.by_position
    order('position ASC')
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails') }

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout "portfolio"
  access all: [:show, :index, :react], user: {except: [:new, :create, :destroy, :edit, :sort ]}, site_admin: :all

  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end

    render nothing: true
  end

  def react
    @react_portfolio_items = Portfolio.react
  end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Your portfolio item is now live.'}
      else
        format.html { render :new}
      end
    end
  end

  def edit
    @portfolio_item = Portfolio.find(params[:id])
  end

  def update
    @portfolio_item = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: "Portfolio was successfully updated." }
      else
        format.html { render :edit}
      end
    end
  end
  
  def show
    @portfolio_item = Portfolio.find(params[:id])
  end

  def destroy
    @portfolio_item = Portfolio.find(params[:id])

    @portfolio_item.destroy

    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully deleted.' }
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      :main_image,
                                      :thumb_image,
                                      technologies_attributes: [:name]
      )
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"    
  end

  def portfolio_img img, type
    if img.model.main_image? || img.model.thumb_image?
      img
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    else
      image_generator(height: '600', width: '400')
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_for(portfolio_item) do |form| %>

<div class="row">
  <div class="col s6">
    <div class="row">
      <div class="input-field col s12">
        <i class="material-icons prefix">text_fields</i>
        <%= form.label :title %> <%= form.text_field :title %>
      </div>
      <div class="input-field col s12">
        <i class="material-icons prefix">text_fields</i>
        <%= form.label :subtitle %> <%= form.text_field :subtitle %>
      </div>
    </div>
  </div>
  <div class="input-field col s6">
    <i class="material-icons prefix">short_text</i>
    <%= form.label :body %> <%= form.text_area :body, class:
    "materialize-textarea" %>
  </div>
  <div class="input-field col s6 ">
    <i class="material-icons prefix">photo</i>
    <label class="btn upload">
      Upload Main Photo <%= form.file_field :main_image, class: 'hide' %>
    </label>
  </div>
  <div class="input-field col s6 margin-top">
    <i class="material-icons prefix">photo</i>
    <label class="btn upload">
      Upload Thumbnail <%= form.file_field :thumb_image, class: 'hide' %>
    </label>
  </div>
</div>

<div class="row">
  <div class="h7">Technologies Used</div>
  <%= form.fields_for :technologies do |technology_form| %>
  <div class="input-field col s6">
    <i class="material-icons prefix">whatshot</i>
    <%= technology_form.label :name %> <%= technology_form.text_field :name %>
  </div>
  <% end %>
</div>

<div class="actions">
  <%= form.submit class: "btn indigo darken-3" %>
</div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="sortable-item col s12 m4" data-id="<%= portfolio_item.id %>">
  <div class="card">
    <div class="card-image">
      <%= image_tag portfolio_img(portfolio_item.thumb_image, 'thumb') %>
    </div>
    <div class="card-action">
      <span class="card-title"></span>
      <%= link_to portfolio_item.title, portfolio_path(portfolio_item)
        %>
        </span>
        <p>
          <%= portfolio_item.subtitle %>
        </p>
    </div>
  </div>
</div>

app/views/portfolios/edit.html.erb
<h1>Edit This Portfolio Item</h1>
<div class="container">
  <%= render "form", portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<%= render 'shared/header', title: "My Portfolio", description: "Check out some
of my projects below. I like to dabble in many technologies but at the core, I
work with JavaScript and Ruby. As for backend, I love using Node.js and Ruby on
Rails. My go to frontend framework is React.js" %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="container">
  <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
    <%= render partial: 'portfolio_item', collection: @portfolio_items %>
  </div>
</div>

app/views/portfolios/new.html.erb
<%= render "form", portfolio_item: @portfolio_item %>

app/views/portfolios/react.html.erb
<h1>React Portfolio Items</h1>

<%= link_to "Create a new Portfolio Item", new_portfolio_path %>

<% @react_portfolio_items.each do |portfolio_item| %>
     <p><%= link_to portfolio_item.title, portfolio_path(portfolio_item) %></p>
     <p><%= portfolio_item.subtitle %></p>
     <p><%= portfolio_item.body %></p>
     <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
     <%= link_to "Edit Portfolio", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
     
     <%= link_to "Delete Portfolio", portfolio_path(portfolio_item), method: :delete, data: { confirm: "Are you sure?"} if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/show.html.erb
<%= render 'shared/header', title: @portfolio_item.title, description: "" %>

<div class="container">
  <div class="row">
    <div class="col s12 m4">
      <%= image_tag portfolio_img(@portfolio_item.thumb_image, 'main'), class:
      "responsive-img" %>
    </div>
    <div class="col s12 m8">
      <em><%= @portfolio_item.subtitle %></em>
      <p><%= @portfolio_item.body %></p>

      <h2>Technologies Used:</h2>

      <% @portfolio_item.technologies.each do |t| %>
      <p><%= t.name %></p>
      <% end %> <%= link_to 'edit', edit_portfolio_path(@portfolio_item) if
      logged_in?(:site_admin) %> <%= link_to 'delete',
      portfolio_path(@portfolio_item), method: :delete, data: { confirm: 'Are
      you sure?'} if logged_in?(:site_admin) %>
    </div>
  </div>

  <%= link_to 'View All Porfolio Items', portfolios_path %>
</div>