config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', 
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios do
    put :sort, on: :collection
  end
  get 'react-items', to: 'portfolios#react'

  get 'about-me', to: "pages#about"
  get 'contact', to: "pages#contact"

  resources :posts do
    member do
      post :toggle_status
    end
  end

  root to: "pages#home"
end

app/views/shared/_application_nav.html.erb
<ul id="dropdown1" class="dropdown-content">
  <%= login_helper("navbar-item") %>
</ul>
<nav class="<%= location %> transparent">
  <div class="nav-wrapper">
    <a href="#" data-target="mobile" class="sidenav-trigger"
      ><i class="material-icons">menu</i></a
    >
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li>
        <%= link_to root_path, class: "navbar-item" do %>
        <i class="material-icons">home</i>
        <% end %>
      </li>
      <li>
        <%= link_to about_me_path, class: "navbar-item" do %>
        <i class="material-icons">person</i>
        <% end %>
      </li>
      <li>
        <%= link_to contact_path, class: "navbar-item" do %>
        <i class="material-icons">contacts</i>
        <% end %>
      </li>
      <li><%= link_to 'Blog', posts_path, class: "navbar-item" %></li>
      <li>
        <%= link_to 'Portfolio', portfolios_path, class: "navbar-item" %>
      </li>
      <li>
        <a
          class="dropdown-trigger waves-effect waves-light btn-flat indigo darken-3 white-text"
          href="#!"
          data-target="dropdown1"
          ><i class="material-icons right">arrow_drop_down</i></a
        >
      </li>
    </ul>

    <a href="#" class="brand-logo">Ivan Garcia</a>
  </div>
</nav>
<ul class="sidenav" id="mobile">
  <li>
    <div class="user-view">
      <div class="background">
        <img src="images/office.jpg" />
      </div>
      <a href="#user"><img class="circle" src="images/yuna.jpg"/></a>
      <a href="#name"><span class="white-text name">John Doe</span></a>
      <a href="#email"
        ><span class="white-text email">jdandturk@gmail.com</span></a
      >
    </div>
  </li>
  <li>
    <%= link_to root_path, class: "navbar-item" do %>
    <i class="material-icons">home</i> Home <% end %>
  </li>
  <li>
    <%= link_to about_me_path, class: "navbar-item" do %>
    <i class="material-icons">person</i> About Me <% end %>
  </li>
  <li>
    <%= link_to contact_path, class: "navbar-item" do %>
    <i class="material-icons">contacts</i> Contact <% end %>
  </li>
  <li><%= link_to 'Blog', posts_path, class: "navbar-item" %></li>
  <li>
    <%= link_to 'Portfolio', portfolios_path, class: "navbar-item" %>
  </li>
</ul>

app/views/shared/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Footer Content</h5>
        <p class="grey-text text-lighten-4">
          You can use rows and columns here to organize your footer content.
        </p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2014 Copyright Text
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="header">
    <h1 class="header__title"><%= title %></h1>
    <p class="header__description"><%= description %></p>
    
    <div class="header__actions">
      <%= link_to about_me_path, class: "waves-effect waves-light btn indigo darken-3" do %>
        <%= fa_icon "camera" %> More About Me
      <% end %>
      <%= link_to posts_path, class: "waves-effect waves-light btn white indigo-text text-darken-3" do %>
        <%= fa_icon "camera" %> My Blog
      <% end %>
    </div>
  </header>

app/views/shared/_nav.html.erb
<ul id="dropdown1" class="dropdown-content">
  <%= login_helper("navbar-item") %>
</ul>
<nav class="<%= location %>">
  <div class="nav-wrapper indigo darken-3">
    <a href="#" data-target="mobile" class="sidenav-trigger"
      ><i class="material-icons">menu</i></a
    >
    <a href="#" class="brand-logo">Ivan</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li>
        <%= link_to root_path, class: "navbar-item" do %>
        <i class="material-icons">home</i>
        <% end %>
      </li>
      <li>
        <%= link_to about_me_path, class: "navbar-item" do %>
        <i class="material-icons">person</i>
        <% end %>
      </li>
      <li>
        <%= link_to contact_path, class: "navbar-item" do %>
        <i class="material-icons">contacts</i>
        <% end %>
      </li>
      <li><%= link_to 'Blog', posts_path, class: "navbar-item" %></li>
      <li><%= link_to 'Portfolio', portfolios_path, class: "navbar-item" %></li>
      <li>
        <a
          class="dropdown-trigger waves-effect waves-light btn blue-grey darken-4"
          href="#!"
          data-target="dropdown1"
          ><i class="material-icons right">arrow_drop_down</i></a
        >
      </li>
    </ul>
  </div>
</nav>

<ul class="sidenav" id="mobile">
  <li>
    <%= link_to root_path, class: "navbar-item" do %>
    <i class="material-icons">home</i>
    <% end %>
  </li>
  <li>
    <%= link_to about_me_path, class: "navbar-item" do %>
    <i class="material-icons">person</i>
    <% end %>
  </li>
  <li>
    <%= link_to contact_path, class: "navbar-item" do %>
    <i class="material-icons">contacts</i>
    <% end %>
  </li>
  <li><%= link_to 'Blog', posts_path, class: "navbar-item" %></li>
  <li>
    <%= link_to 'Portfolio', portfolios_path, class: "navbar-item" %>
  </li>
</ul>