config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', 
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios do
    put :sort, on: :collection
  end
  get 'react-items', to: 'portfolios#react'

  get 'about-me', to: "pages#about"
  get 'contact', to: "pages#contact"

  resources :posts do
    member do
      post :toggle_status
    end
  end

  root to: "pages#home"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic, optional: true
  
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :toggle_status]
  layout "post"
  access all: [:show, :index], user: {except: [:new, :create, :destroy, :edit, :toggle_status ]}, site_admin: :all
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @post = Post.last
    @page_title = "Ivan Garcia | Portfolio Blog"
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @page_title = @post.title
    @seo_keywords = @post.title
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
    end
  end

  def toggle_status
    if @post.draft?
      @post.published!
    elsif @post.published?
      @post.draft!
    end
    redirect_to posts_url, notice: "Post status has been updated."
  end

  private

  def set_post
    @post = Post.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_blog-bio.erb
<div class="blog-bio__about">
  <h5>About</h5>
  <p>I'm Ivan, born and raised in the Bronx, New York, but currently living in Japan. If you need a developer that will deliver a project on time and within budget, look no further and contact me. </p>
</div>
<div class="blog-bio__social-media">
  <a href="//www.github.com/ivanvgarcia">
    <%= fa_icon "github" %>
  </a>
  <a href="//www.linkedin.com/in/ivan-garcia-64880651/">
    <%= fa_icon "linkedin" %>
  </a>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<header>
  <h4>
    <%= post.title.upcase %>
  </h4>
</header>
<p><%= distance_of_time_in_words(post.created_at, Time.now) %> ago</p>
<p><%= post.body %></p>
<p>
  <%= link_to post.status, toggle_status_post_path(post), method: :post %>
</p>
<div><%= link_to 'Read More', post,  class: "btn" %></div>
<div>
  <%= link_to 'Edit', edit_post_path(post) if logged_in?(:site_admin) %>
</div>
<div>
  <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?'
  } if logged_in?(:site_admin) %>
</div>

app/views/posts/_post_list.html.erb
<div class="posts-side-menu__post">
  <%= link_to "", post_path(post), class: "posts-side-menu__link", remote: true %>
  <div class="posts-side-menu__actions">
    <% if post.draft? && logged_in?(:site_admin) %>
      <%= link_to toggle_status_post_path(post), method: :post do %>
        <i class="material-icons">publish</i>
      <% end %>
    <% else %>
      <%= link_to toggle_status_post_path(post), method: :post do %>
        <i class="material-icons">drafts</i>
      <% end %>
    <% end %>
    <% if logged_in?(:site_admin) %>
      <%= link_to edit_post_path(post) do %>
        <i class="material-icons">create</i>
      <% end %>

      <%= link_to post_path(post), method: :delete, data: { confirm: 'Are you
      sure?' } do %>
      <i class="material-icons">delete_forever</i>
      <% end %>
    <% end %>
  </div>
  <h6 class="posts-side-menu__title">
    <%= post.title.capitalize %>
  </h6>
  <p class="posts-side-menu__date">
    <%= distance_of_time_in_words(post.created_at, Time.now) %> ago
  </p>
  
</div>

app/views/posts/_post_ruler.html.erb
<hr />

app/views/posts/_show-post.html.erb
<div class="post">
  <% if post.nil? %>
    <h2 class="post__title indigo-text text-darken-3">
      Ivan has not written any posts yet...
    </h2>
    <p class="post__body">
    </p>
  <% else %>
    <div class="post__actions">
      <%= link_to 'Edit', edit_post_path(post), class: "btn indigo" if
      logged_in?(:site_admin) %>
    </div>
    <h2 class="post__title indigo-text text-darken-3">
      <%= post.title %>
    </h2>
    <p class="post__body">
      <%= post.body %>
    </p>
  <% end %>
  
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
  <div class="row is-marginless">
    <div class="col s12 m2 grey lighten-5 posts-side-menu is-paddingless">
      <% @posts.each do |post| %>
        <%= render 'post_list', post: post %>
      <% end %>
    </div>
    <div  class="col s12 m10">
      <div class="blog-title">
        <h1>My Blog</h1>
        <p>A blog focusing on programming</p>
      </div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="row">
        <div id="show-post" class="col m8">
          <%= render "show-post", post: @post %>
        </div>
        <div class="col m4 blog-bio">
            <%= render "blog-bio" %>
        </div>
      </div>
    </div>
  </div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= render "show-post", post: @post %>

app/views/posts/show.js.erb
var postContainer = document.querySelector('#show-post');
var posts = document.querySelectorAll('.posts-side-menu__post');

var showPost = postHTML => {
  postContainer.innerHTML = ""
  postContainer.insertAdjacentHTML('afterbegin', postHTML);
  scrollTo(document.documentElement, 0, 200)
};

function scrollTo(element, to, duration) {
    if (duration <= 0) return;
    var difference = to - element.scrollTop;
    var perTick = difference / duration * 10;

    setTimeout(function() {
        element.scrollTop = element.scrollTop + perTick;
        if (element.scrollTop === to) return;
        scrollTo(element, to, duration - 10);
    }, 10);
}

showPost('<%= j render "show-post", post: @post %>');